include ../Makefile.tests_common

USEMODULE += ng_netbase
USEMODULE += 802154_mac
USEMODULE += ng_pktdump
USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += kw2xrf
USEMODULE += vtimer

include $(RIOTBASE)/Makefile.include
