APPLICATION = ranging_at86rf2xx 
include ../Makefile.tests_common

BOARD_INSUFFICIENT_RAM := stm32f0discovery

# Define default pin mappings for some boards:

USEMODULE += ng_at86rf2xx
USEMODULE += ng_netbase
USEMODULE += ng_nomac
USEMODULE += ng_pktdump
USEMODULE += shell
USEMODULE += shell_commands

include $(RIOTBASE)/Makefile.include
